num1 = int(input("digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
num3 = float(input("Digite o terceiro número: "))
print((2 * num1) * (num2 / 2))
print(num1 + num3)
print(num3 ** 3)